(load "~/.emacs.d/lisp/init-package.el")
(load "~/.emacs.d/lisp/base-config.el")
; (load "~/.emacs.d/elpa/solarized-theme-20160505.133/solarized-light-theme.el")
(load "~/.emacs.d/lisp/monokai-theme.el")
;(load "~/.emacs.d/elpa/flycheck-20160514.1008/flycheck-autoloads.el")
